### ISSUE TITLE
Find a New Maintainer

### ISSUE THREAD

**Issue by gfx** [DrHyde/perl-modules-Sub-Attribute#3]
I no longer use this module, finding a new maintainer for this module.

**Comment by DrHyde** [comment]
If you'll give me a commit bit and PAUSE permission I'll at least apply [this patch](https://rt.perl.org/Public/Bug/Display.html?id=126145#txn-1369209).

**Comment by gfx** [comment]
Great!

Can you tell me your PAUSE id?

**Comment by DrHyde** [comment]
On Tue, May 16, 2017 at 07:57:01PM -0700, FUJI Goro wrote:

> Great!
> 
> Can you tell me your PAUSE id?

DCANTRELL

-- 
David Cantrell | Minister for Arbitrary Justice

  I don't do .INI, .BAT, or .SYS files.  I don't assign apps to files.
  I don't configure peripherals or networks before using them. I have
  a computer to do all that. I have a Macintosh, not a hobby.
        -- Fritz Anderson

**Comment by gfx** [comment]
done!

```console
$ comaint Sub::Attribute DCANTRELL
Going to make DCANTRELL as a comaint of the following modules.

  Sub::Attribute

Are you sure? [y] y

Added DCANTRELL to co-maintainers of Sub::Attribute.
```

And I'm transfering this repo to you.

Thanks!

**Comment by DrHyde** [comment]
I think you need to twiddle something more to transfer the repo ownership - I was hoping that my first action could be to close this issue :-) but I can't.

**Comment by DrHyde** [comment]
I forked and will work there - the new repo is https://github.com/DrHyde/perl-modules-Sub-Attribute

**Comment by gfx** [comment]
<img width="726" alt="screen shot 2017-07-01 at 13 01 59" src="https://user-images.githubusercontent.com/101800/27758979-c9ac03dc-5e5d-11e7-8b26-d57fe0be4648.png">

Curious. I've transfered the repo to you two weeks ago.

Can you remove your fork?  I'll try to transfer it again. I can't do it anymobe because you have the fork.

**Comment by gfx** [comment]
FYI you must "accept" the new ownership somewhere on GitHub.

**Comment by DrHyde** [comment]
That's odd, I never got the notification that I would expect if I have to accept it. Anyway, I've deleted the fork so let's try again.

**Comment by gfx** [comment]
Done. I guess you have notification on your profile pages or the repo page.

**Comment by gfx** [comment]
And I've added you to the collabolators: https://github.com/gfx/Perl-Sub-Attribute/invitations

Maybe it is required before transfering? (not sure).

**Comment by DrHyde** [comment]
Got it! Thanks. Now I can close this ticket :-)

**Comment by gfx** [comment]
👏

Thanks.
