### ISSUE TITLE
Cannot build without . in @INC as of 5.26.0

### ISSUE THREAD

**Issue by toddr** [DrHyde/perl-modules-Sub-Attribute#4]
When you do:
perl526 Makefile.PL, you get:

Can't locate inc/Module/Install.pm in @INC

The easiest fix is to add this to the first line of Makefile.PL

use lib '.';

**Comment by DrHyde** [comment]
Not quite so easy, but better, to ditch Module::Install entirely. Version 0.07 does that and is on its way to the CPAN now. Thanks for the bug report.
